Jahia/luxe-jahia-demo

package.json, tests/package.json, tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/BACKLOG-22604
=> BACKLOG-22604: Switched module version to 0.1.0

src/server/components/TextIllustrated.jsx
https://jira.jahia.org/browse/BACKLOG-22593
Fix TextIllustrated proptypes
=> BACKLOG-22593: Fix TextIllustrated proptypes

definitions.cnd, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, src/server/views/agency/AgencyFullPage.jsx
review the way languages are returned for the agency, now it is the languages spoken by the associated realtors or language based on country code
review content def
review language bundle
no specific JIRA ticket
=> Agency language

src/server/views/navMenu/NavMenuDefault.jsx, src/server/views/navMenu/NavMenuIllustrated.jsx
https://jira.jahia.org/browse/BACKLOG-22611
=> bug fixing, nav not updated correctly in live mode

locales/de.json, locales/en.json, locales/es.json, locales/fr.json, src/server/components/TextIllustrated.jsx, src/server/views/jcrQuery/JcrQueryDefault.jsx, src/server/views/jcrQuery/JcrQueryInline.jsx, src/server/views/jcrQuery/utils.js, src/server/views/navMenu/LanguageSwitcher.jsx, src/server/views/navMenu/NavMenuDefault.jsx, src/server/views/navMenu/NavMenuIllustrated.jsx
add no result in case query doesn't return content
add label in all languages
add warning in case category is deleted and used ase filter by the query
review the code to build the query
=> Query no result

locales/de.json, locales/en.json, locales/es.json, locales/fr.json, package.json, src/server/templates/page/PageDestination.jsx, src/server/views/index.js, src/server/views/page/PageRelatedContent.jsx, src/server/views/page/index.js, yarn.lock
add related RealEstate and Agencies to destination page
update jahia js-server-core to latest release
=> add related RealEstate and Agencies to destination page

src/server/components/Table.jsx, src/server/views/agency/AgencyFullPage.jsx, src/server/views/realtor/RealtorFullPage.jsx
a proposal to manage capitalize in data table
=> Capitalize laguage data tabe

css/editMode.css, resources/luxe-jahia-demo.properties, resources/luxe-jahia-demo_de.properties, resources/luxe-jahia-demo_es.properties, resources/luxe-jahia-demo_fr.properties, src/server/components/ContentHeader.jsx, src/server/components/HtmlFooter.jsx, src/server/views/estate/EstateFullPage.jsx
https://jira.jahia.org/browse/BACKLOG-22725
=> review jcrQuery labels, capitalize Jahia Academy

src/server/components/CMPreview.jsx, src/server/components/HtmlHead.jsx, src/server/views/agency/AgencyDefault.jsx, src/server/views/agency/AgencyFullPage.jsx, src/server/views/estate/EstateDefault.jsx, src/server/views/estate/EstateFullPage.jsx, src/server/views/header/HeaderDefault.jsx, src/server/views/header/HeaderTextDown.jsx, src/server/views/header/HeaderTextUp.jsx, src/server/views/navMenu/NavMenuDefault.jsx, src/server/views/navMenu/NavMenuIllustrated.jsx, src/server/views/page/PageDefault.jsx, src/server/views/realtor/RealtorDefault.jsx, src/server/views/realtor/RealtorFullPage.jsx, src/server/views/textIllustrated/TextIllustratedDefault.jsx
- use BuildUrl() to import static ressource or to build "complex" url like the one in language switcher.
- use <node>.getUrl() for other case.
https://jira.jahia.org/browse/BACKLOG-22778
=> buildUrl & getUrl & jahia app context

webpack.config.js
Added comments to the webpack config
=> Backlog 22489 comment webpack

tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/BACKLOG-23136: update luxe-jahia-demo
Update tests to use latest luxe-demo-SN version, as currently added tests are failing.
=> BACKLOG-23136: update luxe-jahia-demo

package.json
https://jira.jahia.org/browse/BACKLOG-23397
Fix broken images (mostly icons) when opening the _Luxe_ site in _jContent_.
=> BACKLOG-23397: Fix broken icons in editor

src/client/WorkspaceNavigation.jsx
Replaced template string with proper gql variables
I have considered the following implications of my change: 
Security slightly improved here!
=> TECH-2041: introduced variables to graphql query

src/client/LoginComponent.jsx, src/client/LoginForm.jsx
Exact same behavior, improved code quality
=> BACKLOG-23532: refactored login form

package.json, yarn.lock
=> BACKLOG-23445: moved bundled dependencies to dev dependencies

settings/definitions.cnd
Partly reverts Jahia/luxe-jahia-demo#87
=> BACKLOG-23496: keep definitions as is

tests/package.json, tests/yarn.lock
[jira.jahia.org/browse/QABACKLOG-1661](https://jira.jahia.org/browse/QABACKLOG-1661)
=> QABACKLOG-1661: Upgraded cypress base image

src/client/LanguageSwitcherComponent.jsx, src/server/components/HtmlFooter.jsx, src/server/layouts/MainLayout.jsx, src/server/views/agency/AgencyFullPage.jsx, src/server/views/navMenu/LanguageSwitcher.jsx
remove BS.js and update LanguageSwitcher to be an hydrated cmp.
set editable false in AgencyFullPage.jsx to disable the "add anywhere btn"
Fix : https://github.com/Jahia/luxe-jahia-demo/issues/119
=> refactor: remove BS.js and update LanguageSwitcher to be an hydrated cmp.

.github/renovate.yml
Setup Renovate to automatically open a PR when a new version of _@jahia/javascript-modules-library_ is released.
=> ci(dependencies): Setup Renovate for @jahia/javascript-modules-library

package.json, vite.config.mjs, yarn.lock
Added rollup plugin SBOM: https://github.com/janbiasi/rollup-plugin-sbom
> [!TIP]
=> build: produce SBOM during vite build

src/components/BlogPost/fullPage.server.tsx
Fix bug on blog post fullPage
> [!TIP]
=> fix: bug fix on blog Post

package.json
=> chore: bumped min Jahia version to 8.2.1.0

package.json, prettier.config.js, src/commons/ContentHeader.module.css, tsconfig.json, vite.config.mjs, yarn.lock
Bumped all dependencies
> [!TIP]
=> chore: bump jsm to 0.7

tests/provisioning-manifest-snapshot.yml
Updated provisioning to use the latest release of luxe-jahia-demo.
> [!TIP]
=> test: update provisioning with latest release of luxe

src/commons/grid/Row.tsx
Allow raw html in `<Row>`
> [!TIP]
=> fix: allow raw html in Row

packages/template-set/src/commons/map/MapWithPin.client.module.css, packages/template-set/src/components/Realtor/Animate.client.tsx, packages/template-set/src/components/Realtor/default.server.tsx, packages/template-set/src/templates/css/global.module.css
=> fix: bug fix on css

tests/provisioning-manifest-snapshot.yml
Update provisioning with latest luxe-jahia-demo-0.9.0-SNAPSHOT.
> [!TIP]
=> test: Update provisioning-manifest-snapshot.yml

packages/prepackaged-site/pom.xml
Update the prepackaged so that its root is the monorepo
> [!TIP]
=> chore: fix repo root

packages/template-set/src/components/BlogPost/card.module.css, packages/template-set/src/components/BlogPost/card.server.tsx
Blog post card image ratio css fix
> [!TIP]
=> fix: css bug 

packages/template-set/src/components/SearchEstate/SearchEstate.client.tsx, packages/template-set/src/components/SearchEstate/SearchResults.client.module.css, packages/template-set/src/components/SearchEstate/SearchResults.client.tsx, packages/template-set/src/components/SearchEstate/results.server.tsx
=> feat: disable pointer-event in searchEstate editMode.

.github/workflows/manual-run.yml, .github/workflows/nightly-SN.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, tests/.env.example
Migrate to Github packages
> [!TIP]
=> chore: migrate to gh packages
